apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umperium-game-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - game.umperium.com
      secretName: umperium-game-secret
  rules:
    - host: game.umperium.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umperium-frontend
                port:
                  number: 80